var addon = true;
$(document).ready(function () {
    $('#btnAddon').click(function () {
        if(addon){
            $('.addon-item').empty();
            $('#btnAddon').text('Tìm kiếm nâng cao');
            addon = false;
        }
        else{
            let addon_ouput = '';
            addon_ouput+='<div class="search-item">';
            addon_ouput+='<div class="inputdecor">';
            addon_ouput+='<input type="text" name="search3" id="search3">';
            addon_ouput+='<label for="search3" class="lable-name">';
            addon_ouput+='<span class="content-name2">';
            addon_ouput+='Điểm khởi hành';
            addon_ouput+='</span>';
            addon_ouput+='</label>';
            addon_ouput+='</div>';
            addon_ouput+='<div class="inputdecor">';
            addon_ouput+='<input type="text" name="search4" id="search4">';
            addon_ouput+='<label for="search4" class="lable-name">';
            addon_ouput+='<span class="content-name2">';
            addon_ouput+='Điểm đến';
            addon_ouput+='</span>';
            addon_ouput+='</label>';
            addon_ouput+='</div>';
            addon_ouput+='</div>';
            addon_ouput+='<div class="search-item">';
            addon_ouput+='<div class="inputdecor">';
            addon_ouput+='<input type="text" name="search5" id="search5">';
            addon_ouput+='<label for="search5" class="lable-name">';
            addon_ouput+='<span class="content-name2">';
            addon_ouput+='Chủ để tour';
            addon_ouput+='</span>';
            addon_ouput+='</label>';
            addon_ouput+='</div>';
            addon_ouput+='<div class="inputdecor">';
            addon_ouput+='<select name="search6" id="search6">';
            addon_ouput+='<option value="2">Tất cả</option>';
            addon_ouput+='<option value="1">Nước ngoài</option>';
            addon_ouput+='<option value="0">Trong nước</option>';
            addon_ouput+='</select>';
            addon_ouput+='<label for="search6" class="lable-name">';
            addon_ouput+='<span class="content-name2">';
            addon_ouput+='Loại tour';
            addon_ouput+='</span>';
            addon_ouput+='</label>';
            addon_ouput+='</div>';
            addon_ouput+='</div>';
            addon_ouput+='<div class="search-item">';
            addon_ouput+='<div class="inputdecor">';
            addon_ouput+='<input type="number" name="search5" id="search5" min="0">';
            addon_ouput+='<label for="search5" class="lable-name">';
            addon_ouput+='<span class="content-name2">';
            addon_ouput+='Số ngày đi tour';
            addon_ouput+='</span>';
            addon_ouput+='</label>';
            addon_ouput+='</div>';
            addon_ouput+='<div class="inputdecor">';
            addon_ouput+='<input type="text" name="search6" id="search6">';
            addon_ouput+='<label for="search6" class="lable-name">';
            addon_ouput+='<span class="content-name2">';
            addon_ouput+='khoảng giá';
            addon_ouput+='</span>';
            addon_ouput+='</label>';
            addon_ouput+='</div>';
            addon_ouput+='</div>';
            addon_ouput+='<div class="search-item">';
            addon_ouput+='<div class="inputdecor">';
            addon_ouput+='<input type="checkbox" name="search7" id="search7">';
            addon_ouput+='<label for="search7" class="lable-name">';
            addon_ouput+='<span class="content-name2">';
            addon_ouput+='Có áp dụng khuyến mãi';
            addon_ouput+=' </span>';
            addon_ouput+='</label>';
            addon_ouput+='</div>';
            addon_ouput+='<div class="inputdecor">';
            addon_ouput+='<input type="checkbox" name="search8" id="search8">';
            addon_ouput+='<label for="search8" class="lable-name">';
            addon_ouput+='<span class="content-name2">';
            addon_ouput+='Tour trả góp';
            addon_ouput+='</span>';
            addon_ouput+='</label>';
            addon_ouput+='</div>';
            addon_ouput+='</div>';
            $('.addon-item').html(addon_ouput);
            $('#btnAddon').text('Thu gọn');
            addon = true;
        }
    });
});