
var isExtend = false;
$(document).ready(function () {

    $('#btnExtendSearch').click(function () {
        if (isExtend) {
            $('.extend-item').empty();
            $('#btnExtendSearch').text('Tìm kiếm nâng cao');
            isExtend = false;
        }
        else {
            let extend_ouput = '';
            extend_ouput += '<div class="search-item">';
            extend_ouput += '<div class="inputdecor">';
            extend_ouput += '<input type="text" name="search2" id="search2">';
            extend_ouput += '<label for="search2" class="lable-name">';
            extend_ouput += '<span class="content-name2">';
            extend_ouput += 'Điểm khởi hành';
            extend_ouput += '</span>';
            extend_ouput += '</label>';
            extend_ouput += '</div>';
            extend_ouput += '<div class="inputdecor">';
            extend_ouput += '<input type="text" name="search3" id="search3">';
            extend_ouput += '<label for="search3" class="lable-name">';
            extend_ouput += '<span class="content-name2">';
            extend_ouput += 'Điểm đến';
            extend_ouput += '</span>';
            extend_ouput += '</label>';
            extend_ouput += '</div>';
            extend_ouput += '</div>';
            extend_ouput += '<div class="search-item">';
            extend_ouput += '<div class="inputdecor">';
            extend_ouput += '<input type="text" name="search4" id="search4">';
            extend_ouput += '<label for="search4" class="lable-name">';
            extend_ouput += '<span class="content-name2">';
            extend_ouput += 'Chủ để tour';
            extend_ouput += '</span>';
            extend_ouput += '</label>';
            extend_ouput += '</div>';
            extend_ouput += '<div class="inputdecor">';
            extend_ouput += '<select name="search5" id="search5">';
            extend_ouput += '<option value="2">Tất cả</option>';
            extend_ouput += '<option value="1">Nước ngoài</option>';
            extend_ouput += '<option value="0">Trong nước</option>';
            extend_ouput += '</select>';
            extend_ouput += '<label for="search5" class="lable-name">';
            extend_ouput += '<span class="content-name2">';
            extend_ouput += 'Loại tour';
            extend_ouput += '</span>';
            extend_ouput += '</label>';
            extend_ouput += '</div>';
            extend_ouput += '</div>';
            extend_ouput += '<div class="search-item">';
            extend_ouput += '<div class="inputdecor">';
            extend_ouput += '<input type="number" name="search6" id="search6" min="0">';
            extend_ouput += '<label for="search6" class="lable-name">';
            extend_ouput += '<span class="content-name2">';
            extend_ouput += 'Số ngày đi tour';
            extend_ouput += '</span>';
            extend_ouput += '</label>';
            extend_ouput += '</div>';
            extend_ouput += '<div class="inputdecor">';
            extend_ouput += '<input type="text" name="search7" id="search7">';
            extend_ouput += '<label for="search7" class="lable-name">';
            extend_ouput += '<span class="content-name2">';
            extend_ouput += 'khoảng giá';
            extend_ouput += '</span>';
            extend_ouput += '</label>';
            extend_ouput += '</div>';
            extend_ouput += '</div>';
            extend_ouput += '<div class="search-item">';
            extend_ouput += '<div class="inputdecor">';
            extend_ouput += '<input type="checkbox" name="search8" id="search8">';
            extend_ouput += '<label for="search8" class="lable-name">';
            extend_ouput += '<span class="content-name2">';
            extend_ouput += 'Có áp dụng khuyến mãi';
            extend_ouput += ' </span>';
            extend_ouput += '</label>';
            extend_ouput += '</div>';
            extend_ouput += '<div class="inputdecor">';
            extend_ouput += '<input type="checkbox" name="search9" id="search9">';
            extend_ouput += '<label for="search9" class="lable-name">';
            extend_ouput += '<span class="content-name2">';
            extend_ouput += 'Tour trả góp';
            extend_ouput += '</span>';
            extend_ouput += '</label>';
            extend_ouput += '</div>';
            extend_ouput += '</div>';
            $('.extend-item').html(extend_ouput);
            $('#btnExtendSearch').text('Thu gọn');
            isExtend = true;
        }
    });
});